[cowrie]
enabled = true
port = 22,2222
filter = cowrie
logpath = /home/ubuntu/ssh-security-project/honeypot/cowrie/var/log/cowrie/cowrie.log
maxretry = 1
bantime = 86400
findtime = 600
ignoreip = 127.0.0.1/8 ::1 192.168.1.7 192.168.1.0/24
action = iptables-allports[name=cowrie]
         hostsdenyadd[file=/etc/hosts.deny]
